name: release/stable

on: workflow_dispatch

jobs:
  release-please-stable:
    permissions:
      contents: write
      pull-requests: write
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        with:
          # could be changed to `ruby` for a gem down the road
          release-type: ruby
